### ISSUE TITLE
PhantomJS support

### ISSUE THREAD

**Issue by grinor** [hyeonsangjeon/youtube-dl-nas#5]
Hello there I try to download the videos on openload.co,but the youtube-dl tell the error message

"ERROR: PhantomJS executable not found in PATH, download it from http://phantomjs.org"

It would be great if the PhantomJS support can be added, thanks a lot!

**Comment by hyeonsangjeon** [comment]
It looks like you are not using the full URL path.
It happens when you use the following.
'https://openload.co/embed/XXXXXX'
If you have content for the OpenLoad download that you want, right-click on Chrome and select "Copy video address" and enter the full url. I have updated the binary file in the container today, but this method still works.

**Comment by lorezcrash** [comment]
I have this issue and it is intermittent. Sometimes I resubmit the command at the command line, and it goes away. That doesn't always work though.

**Comment by hyeonsangjeon** [comment]
youtube-dl excute file has been updated. It goes well. I will resolve
